# Generated by Django 3.0.6 on 2020-06-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shikihos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shikiho',
            name='next_dividend',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='shikiho',
            name='next_net_income_per_share',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='shikiho',
            name='prev_dividend',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='shikiho',
            name='prev_net_income_per_share',
            field=models.TextField(null=True),
        ),
    ]
